---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-01-challenge
spec:
  acme:
    email: daiquy2903@gmail.com
    # Staging Environment: must be used for testing before using prod env
    # Letsencrypt has a strict rate limit.
    # server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: staging-cluster-issuer
    solvers:
      - selector: {}
        http01:
          ingress:
            class: external-nginx
